### ISSUE TITLE
The counting of Outline pane fails, Obsidian V1.4.16

### ISSUE THREAD

**Issue by wenbopeng** [platon-ivanov/obsidian-heading-counter#16]
The counting of Outline pane fails, Obsidian V1.4.16

![Snipaste_2023-10-17_21-16-22](https://github.com/platon-ivanov/obsidian-visually-numbered-headings/assets/74350447/9a4598fe-fe27-4e7b-b4db-40e71f62701a)

**Comment by wenbopeng** [comment]
I solved it with a modified piece of CSS
```css
/* container of first layer headings. */
.workspace-leaf-content {
  counter-reset: rootCounter;
}

.workspace-leaf-content .tree-item .tree-item-self .tree-item-inner::before {
  content: counters(rootCounter, ".") ". ";
  counter-increment: rootCounter;
}

/* container of the ohter headings. */
/* NOTE: It is not .outline anymore. So we need a new counter */
.tree-item-children {
  counter-reset: innerCounter;
}

.tree-item-children .tree-item .tree-item-self .tree-item-inner::before {
  content: counters(rootCounter, ".") "." counters(innerCounter, ".") ". ";
  counter-increment: innerCounter;
}
```

I found that Obsidian modified the CSS-Class name of the outline, and the previous method failed.

![image](https://github.com/platon-ivanov/obsidian-visually-numbered-headings/assets/74350447/1550e355-8591-40f1-8e2d-f66d504222a1)
