### ISSUE TITLE
FR: HTML attribute or CSS counter instead of generated content

### ISSUE THREAD

**Issue by efrec** [platon-ivanov/obsidian-heading-counter#17]
### Request

Change how decorations are generated or create a user setting for different styles (span, attribute, counter).

### Motivation

I use this plugin for my longform notes (5,000+ words) and numbering their major sections. My daily tasks, content notes, etc.—the majority of my notes—don't need numbering. This pattern seems representative of most Obsidian users. Attributes and counters do not auto-generate content by default so are the more idiomatic solution.

### What I tried

I have done some testing on the idea. I converted the decoration widget (span) to a decoration line (attribute). Instead of adding a span element, then, effectively I do this:

```js
this.containerEl.setAttribute('data-section-counter', this.display);
```

..to produce this:

![image](https://github.com/platon-ivanov/obsidian-visually-numbered-headings/assets/103912894/05aa206c-549d-4797-9d95-3806a9ff2b7d)

Which is very similar, but lets me use a CSS counter as a fallback and adds less generated content to the page. It's also opt-in—nothing shows up until you (e.g.) style a ::before element. Most of my notes don't use numbered headings. Maybe other users of the plugin will disagree. My few notes that do use this are longform notes with chapter/section headings. I can set `cssclasses: longform` to apply a style similar to this:

```css
.longform div:has(>h1) {
  counter-increment: chapters;

  &>h1 {
    &::before {
      content: counter(chapters, upper-roman);
      font-family: var(--section-counter-font, inherit);
    }

    &[data-section-counter]:not([data-section-counter=''])::before {
      content: attr(data-section-counter);
    }
  }
}
```

I made some other tweaks, like supporting some `list-style-type` conversions, that could be incorporated as well to target an audience that wants to customize their documents without first leaving Obsidian. The result is just nice:

![image](https://github.com/platon-ivanov/obsidian-visually-numbered-headings/assets/103912894/8b6ecc5f-0028-41e9-a39c-9f9776011cf5)
